CREATE TABLE "FoodEntry" (
  "id" SERIAL PRIMARY KEY,
  "date" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "calories" INTEGER NOT NULL,
  "protein" DOUBLE PRECISION NOT NULL,
  "carbs" DOUBLE PRECISION NOT NULL,
  "fat" DOUBLE PRECISION NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "WeightEntry" (
  "id" SERIAL PRIMARY KEY,
  "date" TEXT NOT NULL UNIQUE,
  "weight" DOUBLE PRECISION NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "CardioEntry" (
  "id" SERIAL PRIMARY KEY,
  "date" TEXT NOT NULL UNIQUE,
  "done" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
